# lightning.pytorch==2.0.0
name: dqn-cartpole
version: v0

seed_everything: 42
trainer:
  max_epochs: 300
  # val_check_interval: 50
  check_val_every_n_epoch: 50
  logger:
    init_args:
      monitor_gym: true

model:
  class_path: module.dqn.DQNModule
  init_args:
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-2
    env: CartPole-v1
    env_kwargs:
      render_mode: rgb_array

ckpt_path: null
