# lightning.pytorch==2.0.0
name: dqn-cartpole
version: map_ds

seed_everything: 42
trainer:
  max_epochs: 150
  # val_check_interval: 50
  check_val_every_n_epoch: 50

model:
  class_path: agents.dqn.DQNModule
  init_args:
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-2
    env: 
      class_path: envs.generator.GymEnvGenerator
      dict_kwargs:
        id: CartPole-v1
        render_mode: rgb_array
        
ckpt_path: null

