project: debug # wandb project name
name: dev-wandb-sweep-4 # wandb sweep name displayed in the UI

program: src/main.py
method: bayes
metric:
  name: val/acc
  goal: maximize
parameters:
  data.batch_size:
    values: [32, 64, 128]

command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "configs/config.yaml" # path to default config file
  - "--name"
  - "dev-wandb-sweep-4" # name of saved logs
  - "--increment_version"
  - ${args}
